# Generated by Django 6.0.1 on 2026-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
